# Generated by Django 3.2.3 on 2021-05-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0002_auto_20210511_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car_kind',
        ),
    ]
