# Generated by Django 3.2.3 on 2021-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0003_remove_user_car_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(max_length=250),
        ),
    ]
