# Generated by Django 3.2.2 on 2021-05-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0004_alter_user_user_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='serial_no2',
        ),
    ]
