# Generated by Django 3.2.2 on 2021-05-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0005_remove_user_serial_no2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour0', models.IntegerField()),
                ('hour1', models.IntegerField()),
                ('hour2', models.IntegerField()),
                ('hour3', models.IntegerField()),
                ('hour4', models.IntegerField()),
                ('hour5', models.IntegerField()),
                ('hour6', models.IntegerField()),
                ('hour7', models.IntegerField()),
                ('hour8', models.IntegerField()),
                ('hour9', models.IntegerField()),
                ('hour10', models.IntegerField()),
                ('hour11', models.IntegerField()),
                ('hour12', models.IntegerField()),
                ('hour13', models.IntegerField()),
                ('hour14', models.IntegerField()),
                ('hour15', models.IntegerField()),
                ('hour16', models.IntegerField()),
                ('hour17', models.IntegerField()),
                ('hour18', models.IntegerField()),
                ('hour19', models.IntegerField()),
                ('hour20', models.IntegerField()),
                ('hour21', models.IntegerField()),
                ('hour22', models.IntegerField()),
                ('hour23', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysisApp.user')),
            ],
        ),
    ]
